import 'package:json_annotation/json_annotation.dart';

part 'challenge.g.dart';

@JsonSerializable()
// Generated by https://quicktype.io

class Challenge {
  int id;
  String createdAt;
  String updatedAt;
  String title;
  String description;
  String photoUrl;
  String location;
  int points;
  bool isenable;

  Challenge({
    this.id,
    this.createdAt,
    this.updatedAt,
    this.title,
    this.description,
    this.photoUrl,
    this.location,
    this.points,
    this.isenable,
  });

  factory Challenge.fromJson(Map<String, dynamic> json) =>
      _$ChallengeFromJson(json);
  Map<String, dynamic> toJson() => _$ChallengeToJson(this);
}
